remote_theme: jekyll-theme-plain/jekyll-theme-plain

title: yuuki
url: https://yuukikonno.com
license: https://creativecommons.org/licenses/by-sa/4.0/
stylesheets:
  - base.css

exclude:
  - 404.html
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

permalink: /blog/:title

collections:
  pages:
    output: true
    permalink: /:title/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: base
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
