remote_theme: jekyll-theme-plain/jekyll-theme-plain

title: yuuki
url: https://yuukikonno.com
license_url: https://creativecommons.org/licenses/by-sa/4.0/

exclude:
  - Gemfile*
  - LICENSE
  - README.md

permalink: /blog/:title

collections:
  pages:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      layout: base
  - scope:
      path: ""
      type: posts
    values:
      layout: post
