title: yuuki's blog
lang: en-US
license_url: https://creativecommons.org/licenses/by-sa/4.0/
permalink: /blog/:title

collections:
  pages:
    output: true
    permalink: /:title

remote_theme: jekyll-theme-plain-text/jekyll-theme-plain-text
