remote_theme: jekyll-theme-plain/jekyll-theme-plain

lang: en-US
title: yuuki
url: https://yuukikonno.com
license_url: https://creativecommons.org/licenses/by-sa/4.0/
stylesheets:
  - default.css

exclude:
  - Gemfile*
  - LICENSE*
  - README*

permalink: /blog/:title

collections:
  pages:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      stylesheets:
        - post.css
